FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

ENV ASPNETCORE_URLS http://*:80
ENV ASPNETCORE_ENVIRONMENT=Development

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["dss.api/dss.api.csproj", "dss.api/"]
RUN dotnet restore "dss.api/dss.api.csproj"
COPY . .
WORKDIR "/src/dss.api"
RUN dotnet build "dss.api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "dss.api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "dss.api.dll"]
