name: GitHub Action Demo
on: [push]    

jobs:
   build:
     runs-on: ubuntu-latest    
     steps:
      - uses: actions/checkout@v2  
      #- run: export GITHUB_TOKEN=
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
      - run: |
         echo ${{ secrets.PAT_TOKEN_CLASSIC }} | gh auth login --with-token
         gh api -X GET /repos/${{ GITHUB.REPOSITORY }}/topics --jq='.names'  
      - run: gh auth status --show-token     
      - run: gh codespace list      
      - run: gh codespace ssh -c mukundnarayanjha-solid-zebra-5xxjwwq45jvcvxq4     
      - run: cd .. 
     
        
