name: GitHub Action Demo
on: [push]    

jobs:
   build:
     runs-on: ubuntu-latest    
     steps:
      - uses: actions/checkout@v2  
      #- run: export GITHUB_TOKEN=
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
         echo ${{ secrets.PAT_TOKEN }} | gh auth login --with-token
         gh api -X GET /repos/${{ GITHUB.REPOSITORY }}/topics --jq='.names'  
      
      - run:  gh auth refresh
      - run:  gh codespace list      
      - run:  gh codespace ssh 
        
